metric_files:
  capacity: "cap.csv"
  generation: "gen_ann.csv"
  emissions: "emit_irt.csv"
  system costs: "systemcost_techba.csv"
  bulk costs: "systemcost_techba_bulk_ew.csv"
  net imports: "net_import_ann_rep.csv"
  health damages: "health_damages_caused_r.csv"
  transmission mw-mi: "tran_mi_out_detail.csv"
  transmission mw: "tran_cap_energy.csv"
  social cost of carbon: "scc_values.csv"
  new capacity additions: "cap_new_ivrt.csv"
  natural gas price: "repgasprice_r.csv"

analysis_year: 2024
social_discount_rate: 0.02  # 2%

